let audio = [
    game_music = new Audio('./audio/music.mp3'),
    walking_sound = new Audio('./audio/walking.mp3'),
    jumping_sound = new Audio('./audio/jump.mp3'),
    hurting_sound = new Audio('./audio/hurt.mp3'),
    dying_sound = new Audio('./audio/dying.mp3'),
    hitChicken = new Audio('./audio/chicken.mp3'),
    bottle_collect_sound = new Audio('./audio/bottles.mp3'),
    coins_collect_sound = new Audio('./audio/collect-coins.mp3'),
    newHP_sound = new Audio ('./audio/heartbeat.mp3'),
    hitEndboss_sound = new Audio('./audio/hit_endboss.mp3'),
    endboss_spawning_sound = new Audio('./audio/spawn_endboss.mp3'),
    throwing_sound = new Audio('./audio/throw.mp3'),
    win_sound = new Audio('./audio/win.mp3'),
    loose_sound = new Audio('./audio/loose.mp3'),
] 